### ISSUE TITLE
ทำอะไรเพิ่มดี 

### ISSUE THREAD

**Issue by NantipatSoftEn** [NantipatSoftEn/TestFlowBrach#3]
### คิดไม่ออกว่าจะ pull อะไรดี

**Comment by 0pdd** [comment]
@NantipatSoftEn the puzzle [#4](https://github.com/NantipatSoftEn/TestFlowBrach/issues/4) is still not solved.

**Comment by 0pdd** [comment]
@NantipatSoftEn the puzzle [#5](https://github.com/NantipatSoftEn/TestFlowBrach/issues/5) is still not solved; solved: [#4](https://github.com/NantipatSoftEn/TestFlowBrach/issues/4).

**Comment by 0pdd** [comment]
@NantipatSoftEn all 2 puzzles are solved here: [#4](https://github.com/NantipatSoftEn/TestFlowBrach/issues/4), [#5](https://github.com/NantipatSoftEn/TestFlowBrach/issues/5).
